### ISSUE TITLE
Provide access to original attributes

### ISSUE THREAD

**Issue by gaaf** [mvanduijker/laravel-transactional-model-events#12]
Hi,

Is there some smart way to somehow access the original attributes?

At the time the (`updated`/`saved`) transactional event fires, Laravel has already called` syncOriginal()`, so `getOriginal()` returns the updated attributes instead of the originals.

I could probably save the originals inside another attribute of the model class from within Laravels own `updated` or `saved` event. But maybe there is a way to access them in a simpler way/

**Comment by mvanduijker** [comment]
Hey!

I have looked into the Laravel code and indeed after a model is saved, the originals get synced so you lose the ability to get originals in the after commit events. I would probably go for the solution you proposed. If you do find a simple way let me know so we could check if we can add it to this package.

**Comment by gaaf** [comment]
I tried my own suggestion, but getting it in a state that also enabled the convenience function like `isDirty()` and `hasChanged()` was too much of a hassle. I decided to just skip the transactional integrity and use Laravel's `updated` and `saved` events.
