### ISSUE TITLE
Don't work with laravel/framework v6.9.0

### ISSUE THREAD

**Issue by 4n70w4** [mvanduijker/laravel-transactional-model-events#3]
`afterCommitCreated` don't fired via observer.
But work with 6.6.1

**Comment by mvanduijker** [comment]
Thanks for your report. It seems to stop working from 6.9 (6.8 still seemed to work) I got the tests to fail on master. Will take a look in the coming days. If you have time, feel free to make a PR.

**Comment by mvanduijker** [comment]
Did a bit more investigation, https://github.com/laravel/framework/pull/30883 is the PR that broke it.

**Comment by mvanduijker** [comment]
I created an issue https://github.com/laravel/framework/issues/30948. Let's see what happens. If it's gonna stick, I have to release a new version for Laravel 6.9+

**Comment by 4n70w4** [comment]
Maybe should make temporarily constraint the laravel version in dependencies of composer.

**Comment by mvanduijker** [comment]
The change in Laravel has been reverted and has been released (6.10.0). I released version 2.1.0 with a constraint not supporting Laravel 6.9.0.

Thanks for the bug report!
