### ISSUE TITLE
Support for multiple connection

### ISSUE THREAD

**Issue by Grummfy** [mvanduijker/laravel-transactional-model-events#4]
Hello,
the trait is very usefull but it doesn't handle multiple connection

**Comment by mvanduijker** [comment]
Thanks for reporting this issue. 
How do you utilise multiple database connections? On the connection property of the model?

**Comment by Grummfy** [comment]
Hello, it depends. Most of the time it's indeed in the model itself. But sometimes it's dynamically setted.

In any case, when you have a model instance, you have the connection string setted inside the model.

I think it's quiete easy to handle static connection, but dynamic one, are probably a bit more complex.

**Comment by mvanduijker** [comment]
How do you expect this to work? The events are fired when all transactions of any database connection are committed, or just the transaction defined in the model.

**Comment by Grummfy** [comment]
if an event occurs in connection A, the after commit transaction related to A (DB::connection(a)->transactionLevel() ...)  should release even related to this level of this connection.

Not sure if I'm clear

**Comment by mvanduijker** [comment]
I added support for multiple database connections in master branch. Could you check if this works out for you?

**Comment by Grummfy** [comment]
seems perfect! thanks for it

**Comment by mvanduijker** [comment]
Nice! I just released a new version with the fix.
