### ISSUE TITLE
afterCommitCreated in observer does not work аfter update from 2.0.1 to 2.3.0

### ISSUE THREAD

**Issue by 4n70w4** [mvanduijker/laravel-transactional-model-events#5]

**Comment by 4n70w4** [comment]
On 2.2.0 also don't work

**Comment by mvanduijker** [comment]
Thanks for the report. I added a test https://github.com/mvanduijker/laravel-transactional-model-events/blob/master/tests/Feature/TransactionalAwareEventsTest.php#L143, but it doesn't fail. Could you check what is different in your case so we can find out what is going wrong?

**Comment by 4n70w4** [comment]
For `created` event `$model->getConnectionName()` is `null`.

But for `saved` event  `$model->getConnectionName()` is `mysql`.

`TransactionCommitted` `$event->connectionName` is `mysql` and `created` event with `null` connetion skipped!


Laravel changed connection after `created` but before `saved` events

`vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:669`

```php
   /**
     * Save the model to the database.
     *
     * @param  array  $options
     * @return bool
     */
    public function save(array $options = [])
    {
...
        if ($this->exists) {
...
        else {
            $saved = $this->performInsert($query);

            if (! $this->getConnectionName() &&
                $connection = $query->getConnection()) {
                $this->setConnection($connection->getName());
            }
        }
```

```
laravel/framework                                v6.6.1
```

**Comment by mvanduijker** [comment]
hmmm so the sqlite driver is doing this differently compared to the mysql driver. I will try to take a look as soon as possible. Will probably have to add a patch to correctly hand null connections. (which is kind a weird imho how can you emit a created event without a database connection)

**Comment by mvanduijker** [comment]
How do you create the model?

**Comment by 4n70w4** [comment]
@mvanduijker 
![image](https://user-images.githubusercontent.com/38257723/86119597-76aee900-badb-11ea-9200-0aefa2dd5bdd.png)

**Comment by mvanduijker** [comment]
You just do Resolution::create(...)?

**Comment by 4n70w4** [comment]
@mvanduijker I use CRUD of Laravel Nova

`\Laravel\Nova\Http\Controllers\ResourceStoreController::handle`

```php
        $model = DB::transaction(function () use ($request, $resource) {
...
                $model->save();
...
            return $model;
        });
```

**Comment by mvanduijker** [comment]
I'm looking for a way to make this fail with a unit test. I couldn't get it to a state where it didn't have a connection name. 
How is $model instantiated?

**Comment by 4n70w4** [comment]
```php
            [$model, $callbacks] = $resource::fill(
                $request, $resource::newModel()
            );
```


```php
    /**
     * Get a fresh instance of the model represented by the resource.
     *
     * @return mixed
     */
    public static function newModel()
    {
        $model = static::$model;

        return new $model;
    }
```

Maybe something strange is happening in `$resource::fill()`. There is a lot of confusing logic.

**Comment by mvanduijker** [comment]
how is $resource declared?

**Comment by 4n70w4** [comment]
You can watch it yourself or contact the developers of https://nova.laravel.com/

**Comment by mvanduijker** [comment]
Could you point me to the correct part of the documentation? I haven't worked with nova yet.

I am looking for a way to replicate your problem. Calling save on a new model without a connection.

**Comment by mvanduijker** [comment]
@4n70w4 I added a fix on master, could you try if this works for you?

**Comment by 4n70w4** [comment]
Hi! I do not plan to update the packages in the near future and I cannot see your fix yet.

Now I'm trying to check firing `afterCommit` events in my application tests.
In my tests, I definitely need to call `Event::fake();`  for prevent run observers of nested models.
But in this case, your events don't fire.

> The expected [eloquent.afterCommit.created: Model] event was not dispatched.

```php
    public function testObserver() {
        Event::fake();

        $model = factory(Model::class)->create();

        Event::assertDispatched('eloquent.creating: ' . Model::class);
        Event::assertDispatched('eloquent.created: ' . Model::class);

        \DB::commit();

        Event::assertDispatched('eloquent.afterCommit.created: ' . Model::class);
    }
```

**Comment by mvanduijker** [comment]
When you fake the events, the transaction committed / rollback events won't get fired. Testing it this way won't work.
> and I cannot see your fix yet.
Where did you look?

**Comment by 4n70w4** [comment]
@mvanduijker wrong translation. I mean: I won't watch yet. I working on other tasks.

Maybe you have ideas on how to test firing afterCommit events without launching observers for existing models.

About null connection:

$model = 'Just\Model'

![image](https://user-images.githubusercontent.com/38257723/88046447-bf951300-cb58-11ea-8a93-1e28510e93a4.png)

**Comment by mvanduijker** [comment]
> About null connection:

That's what I fixed in master (https://github.com/mvanduijker/laravel-transactional-model-events/blob/master/src/TransactionalAwareEvents.php#L35) I hope this works for you.

About testing: I would unit test the Observer class and have an integration or e2e test to make sure it works as expected.

**Comment by mvanduijker** [comment]
It should be fixed with https://github.com/mvanduijker/laravel-transactional-model-events/commit/cceb4b363ee526bba4bd67ea798e0b4736ef1529
