### ISSUE TITLE
event gets fired twice

### ISSUE THREAD

**Issue by michabbb** [mvanduijker/laravel-transactional-model-events#6]
hi,

i don´t know if i am doing something wrong. i am saving an "order" and its "order_items" inside a transaction.
in the model "order" i am using this code:

```php
protected static function booted(): void {
        static::registerModelEvent('afterCommit.saved', static function ($order) {
            $order->notifyNow(new NewOrderCreated($order));
        });
    }
```

i am using the construct:

```php
DB::transaction(function () {
    ..........
});
```

my problem is, that the notification (email) is sent twice.
i am using laravel `7.16.1` and `2.3.1` of this package.

am i doing something wrong ??

btw... i don´t understand the difference between `afterCommit.created` and `afterCommit.saved`, but problems exists on both events.

thanks for any help!

**Comment by mvanduijker** [comment]
You can read about the difference between created, saved and updated in the documentation of Laravel https://laravel.com/docs/7.x/eloquent#events

I can not reproduce events getting fired twice. Are you by chance still firing the regular (none transactional) events? Maybe in with an observer?

**Comment by michabbb** [comment]
thanks for your feedback. I don't think so. could you please provide me with a code snippet that allows me to log every event that gets fired so I can debug this? pardon, I am new to this whole event thing in laravel...

**Comment by mvanduijker** [comment]
You can try a wildcard listener, check the Laravel documentation https://laravel.com/docs/7.x/events#manually-registering-events

**Comment by michabbb** [comment]
interesting... this is what happens when saving my order....
```
[2020-09-07 11:11:14] local.DEBUG: eloquent.saving: App\Models\Produkte\order [{"App\\Models\\Produkte\\order":{...}}] 
[2020-09-07 11:11:14] local.DEBUG: eloquent.creating: App\Models\Produkte\order [{"App\\Models\\Produkte\\order":{"..."}}] 
[2020-09-07 11:11:14] local.DEBUG: eloquent.created: App\Models\Produkte\order [{"App\\Models\\Produkte\\order":{"...}}] 
[2020-09-07 11:11:14] local.DEBUG: eloquent.saved: App\Models\Produkte\order [{"App\\Models\\Produkte\\order":{"...}}] 
[......]
[2020-09-07 11:11:16] local.DEBUG: eloquent.afterCommit.created: App\Models\Produkte\order [{"App\\Models\\Produkte\\order":{"...}}] 
[2020-09-07 11:11:16] local.DEBUG: eloquent.afterCommitCreated: App\Models\Produkte\order [{"App\\Models\\Produkte\\order":{"...}}] 
[2020-09-07 11:11:16] local.DEBUG: eloquent.afterCommit.saved: App\Models\Produkte\order [{"App\\Models\\Produkte\\order":{"...}}] 
[2020-09-07 11:11:16] local.DEBUG: eloquent.afterCommitSaved: App\Models\Produkte\order [{"App\\Models\\Produkte\\order":{"...}}] 

```
what i am doing is pretty simple and common:

```php
return DB::connection('mysql')->transaction(static function () use ($request, $OrderCode) {
            $Order                         = new order();
            // assign fields with values
            $Order->save();
            foreach ($order_items as $k_id => $k_stuecke) {
                $OrderItem            = new order_items();
                // assign fields with values
                $OrderItem->save();
            }

            return $OrderCode;
        }, 5);
```

is it possible, that the event gets fired twice because `eloquent.afterCommitSaved` and `eloquent.afterCommit.saved` are handled identically ?

**Comment by mvanduijker** [comment]
I only see the event triggered once in your log.

`eloquent.afterCommitSaved` is some kind of alias to `eloquent.afterCommit.saved` to support observers (Laravel doesn't like dots in event names for observers). They both indeed get triggered, but you listen to only 1 of them.

My guess it something with your `order_item` does it touch / update the parent (`order`) when you save it?

**Comment by michabbb** [comment]
puh... exhausting....  i completely removed "order_item" inside my transaction and still, the emails gets send twice... i will dig deeper.... 🤔

**Comment by michabbb** [comment]
okay, inside my model "order" i made a test....

```php
static::registerModelEvent('afterCommit.saved', static function ($order) {
            \Log::debug('afterCommit.saved got fired....');
        });
```
and the log file confirms, that this event only got fired once.
so it must have something to do with `$order->notify(....)` , but i still have no idea....

interesting.... 🤔

**Comment by michabbb** [comment]
![](https://media.giphy.com/media/cLqTJKTNfhsPK/giphy.gif)

oh boy... this is so stupid... 🙄 
i am testing the emails with mailtrap - so guess what happens if you have a "bcc" in your email, right...
mailtrap will show 2️⃣ individual emails

![](https://media.giphy.com/media/9mWg0JLV4NwM8/giphy.gif)

sorry for stealing your time.... 😢 🙈

**Comment by mvanduijker** [comment]
hahaha, happy you solved this issue 🎉
